### PR TITLE
Add fetch tweet API

### PR DESCRIPTION
**Pull request by yamade**
## Summary
-  Added to API to fetch single tweet
-  Fix for https://github.com/tkporter/react-native-fabric-twitterkit/issues/4

## Changes
-  Added `jsonToWritableMap`
-  Modified `fetchProfile ()` to use `jsonToWritableMap `
-  Added `fetchTweet()` API

### CODE REVIEW

**Comment by Liroo** [comment]
@yamade we have to sign in to be able to load this tweet ?

**Comment by yamade** [comment]
@Liroo Yes, we have to.

**Comment by tkporter** [comment]
Hey @yamade, this looks great! Sorry it took so long to get back to you on this.

Really appreciate you contributing, I'm going to add this to version 0.1.0 on npm. Thanks!

**Comment by yamade** [comment]
@tkporter Thanks to merge the PR and include to 0.1.0!

**Pull request merged**
