### PR TITLE
   Android throws error "Service methods cannot return void.\n for method CustomService.show" on calling fetchProfile method

### LINKED ISSUE #19: Android Error: Service methods cannot return void
Android throws error "Service methods cannot return void.\n for method CustomService.show" on calling fetchProfile method

### PR DESCRIPTION
**Pull request by aby040**
This fixes #19. Android throws error "Service methods cannot return void.\n for method CustomService.show" on calling fetchProfile method

### CODE REVIEW

**Comment by aby040** [comment]
fixes #19

**Comment by prtkkmrsngh** [comment]
This is isn't fixing the issue.

**Comment by prtkkmrsngh** [comment]
My bad....it is fixing the issue. @tkporter please merge this PR
Thanks

**Comment by tkporter** [comment]
Hey @aby040 could you resolve these conflicts? I'm happy to merge when they're resolved!

**Comment by aby040** [comment]
@tkporter Done 👍

**Pull request merged**
