### PR TITLE
Upgrade TwitterKit for Android

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by tkporter** [comment]
@mehcode are there any breaking changes with this update?

**Comment by mehcode** [comment]
Not as far as I can tell? I only use this for login though.

**Comment by mdstaff** [comment]
Has this been merged?

**Comment by appden** [comment]
Hello. It would be really nice to see this merged. Thanks!

**Comment by tkporter** [comment]
@appden @mehcode  @mdstaff Merging this in and I'll publish to 0.3.0 with the changes!

**Comment by appden** [comment]
@tkporter Thank you! :tada:

**Pull request merged**
